
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(667, 469)
        MainWindow.setMinimumSize(QSize(667, 469))
        MainWindow.setMaximumSize(QSize(667, 469))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(130, 20, 411, 81))
        font = QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)
        self.ws = QLineEdit(self.centralwidget)
        self.ws.setObjectName(u"ws")
        self.ws.setGeometry(QRect(70, 220, 201, 21))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(70, 120, 191, 51))
        font1 = QFont()
        font1.setBold(True)
        font1.setWeight(QFont.Weight.Bold)
        self.label_2.setFont(font1)
        self.label_2.setTextFormat(Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(130, 170, 71, 41))
        font2 = QFont()
        font2.setFamily(u"Perpetua Titling MT")
        font2.setPointSize(18)
        font2.setBold(False)
        font2.setWeight(QFont.Weight.Bold)
        self.label_3.setFont(font2)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.generarGrafica = QPushButton(self.centralwidget)
        self.generarGrafica.setObjectName(u"generarGrafica")
        self.generarGrafica.setGeometry(QRect(110, 270, 131, 51))
        self.n1 = QLineEdit(self.centralwidget)
        self.n1.setObjectName(u"n1")
        self.n1.setGeometry(QRect(410, 150, 201, 21))
        self.n2 = QLineEdit(self.centralwidget)
        self.n2.setObjectName(u"n2")
        self.n2.setGeometry(QRect(410, 210, 201, 21))
        self.n3 = QLineEdit(self.centralwidget)
        self.n3.setObjectName(u"n3")
        self.n3.setGeometry(QRect(410, 270, 201, 21))
        self.n4 = QLineEdit(self.centralwidget)
        self.n4.setObjectName(u"n4")
        self.n4.setGeometry(QRect(410, 330, 201, 21))
        self.n5 = QLineEdit(self.centralwidget)
        self.n5.setObjectName(u"n5")
        self.n5.setGeometry(QRect(410, 390, 201, 21))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(470, 110, 71, 41))
        self.label_4.setFont(font2)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(470, 170, 71, 41))
        self.label_5.setFont(font2)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(470, 230, 71, 41))
        self.label_6.setFont(font2)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(470, 290, 71, 41))
        self.label_7.setFont(font2)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(470, 350, 71, 41))
        self.label_8.setFont(font2)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.allRandom = QPushButton(self.centralwidget)
        self.allRandom.setObjectName(u"allRandom")
        self.allRandom.setGeometry(QRect(110, 360, 131, 51))
        self.allRandom.setCursor(QCursor(Qt.ArrowCursor))
        self.allRandom.setAcceptDrops(False)
        self.allRandom.setAutoFillBackground(False)
        self.allRandom.setAutoRepeat(False)
        self.allRandom.setAutoExclusive(False)
        self.allRandom.setAutoDefault(False)
        self.allRandom.setFlat(False)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.allRandom.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Entrenamiento de neuronas", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Si no quieres pesos aleatorios escribe los pesos separados por comas", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"W1-6", None))
        self.generarGrafica.setText(QCoreApplication.translate("MainWindow", u"Generar grafica", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u03b71", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u03b72", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u03b73", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u03b74", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u03b75", None))
        self.allRandom.setText(QCoreApplication.translate("MainWindow", u"Todo aleatorio", None))
    # retranslateUi

